# 01. Tiền xử lý dữ liệu

Notebook này trình bày cách nhóm đọc bộ dữ liệu `Online Retail.xlsx`, làm sạch các dòng không phù hợp và tạo dữ liệu dạng basket để chạy thuật toán ECLAT.

File `baskets.csv` dùng `Description` làm item để kết quả dễ đọc. Cột `Items` được lưu dưới dạng JSON list, vì một số tên sản phẩm có dấu phẩy và không thể tách item bằng dấu phẩy thông thường.

In [1]:
from pathlib import Path
import os
import json

import pandas as pd

## 1. Đọc dữ liệu gốc

In [2]:
def find_project_root(start: Path) -> Path:
    candidates = [start, *start.parents]
    candidates += [
        start / "Data-Mining-Group-7",
        start / "Project" / "Data-Mining-Group-7",
        Path.home() / "Desktop" / "Project" / "Data-Mining-Group-7",
    ]

    for path in candidates:
        path = path.resolve()
        if (path / "data" / "raw" / "Online Retail.xlsx").exists():
            return path
    raise FileNotFoundError("Khong tim thay thu muc do an Data-Mining-Group-7.")


project_root = find_project_root(Path.cwd().resolve())
os.chdir(project_root)

raw_data_path = Path("data/raw/Online Retail.xlsx")
print(f"Doc du lieu tu: {raw_data_path}")

df = pd.read_excel(raw_data_path)
print(f"Du lieu goc: {df.shape[0]} dong, {df.shape[1]} cot")
df.head()

Doc du lieu tu: data\raw\Online Retail.xlsx

Du lieu goc: 541909 dong, 8 cot

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

## 2. Làm sạch dữ liệu

Nhóm giữ lại các dòng có thể dùng cho bài toán luật kết hợp:

- Bỏ dòng thiếu `Description` hoặc `InvoiceNo`.
- Chuẩn hóa `Description` bằng cách xóa khoảng trắng thừa ở đầu/cuối.
- Bỏ hóa đơn hủy, tức `InvoiceNo` có chứa ký tự `C`.
- Chỉ giữ giao dịch có `Quantity > 0`.
- Chỉ giữ `StockCode` có dạng mã sản phẩm thật: 5 chữ số, có thể kèm 1 chữ cái.

In [3]:
# Bỏ dòng thiếu tên sản phẩm
before_rows = df.shape[0]
df.dropna(axis=0, subset=["Description"], inplace=True)

# Chuẩn hóa tên sản phẩm
df["Description"] = df["Description"].astype(str).str.strip()

# Bỏ dòng thiếu mã hóa đơn
df.dropna(axis=0, subset=["InvoiceNo"], inplace=True)
df["InvoiceNo"] = df["InvoiceNo"].astype(str)

# Bỏ hóa đơn hủy
cancelled_rows = df["InvoiceNo"].str.contains("C").sum()
df = df[~df["InvoiceNo"].str.contains("C")]

# Chỉ giữ số lượng mua hợp lệ
df = df[df["Quantity"] > 0]

# Giữ mã sản phẩm có dạng 5 chữ số, có thể kèm 1 chữ cái
df["StockCode"] = df["StockCode"].astype(str)
df = df[df["StockCode"].str.match(r"^\d{5}[a-zA-Z]?$")]

print(f"So dong ban dau: {before_rows}")
print(f"So hoa don huy da bo: {cancelled_rows}")
print(f"So dong sau lam sach: {df.shape[0]}")
print(f"So StockCode rieng biet: {df['StockCode'].nunique()}")
print(f"So InvoiceNo rieng biet: {df['InvoiceNo'].nunique()}")

So dong ban dau: 541909
So hoa don huy da bo: 9288
So dong sau lam sach: 527919
So StockCode rieng biet: 3901
So InvoiceNo rieng biet: 19952

## 3. Tạo bảng ánh xạ mã sản phẩm

Bảng này giúp tra cứu `StockCode -> Description` khi cần đối chiếu mã sản phẩm với tên sản phẩm.

In [4]:
mapping = df.groupby("StockCode")["Description"].first().reset_index()

processed_dir = Path("data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

mapping_path = processed_dir / "stockcode_description_map.csv"
mapping.to_csv(mapping_path, index=False)

print(f"Da luu bang mapping tai: {mapping_path}")
print(f"So ma san pham trong mapping: {mapping.shape[0]}")
mapping.head(10)

Da luu bang mapping tai: data\processed\stockcode_description_map.csv

So ma san pham trong mapping: 3901

  StockCode                   Description
0     10002    INFLATABLE POLITICAL GLOBE
1     10080      GROOVY CACTUS INFLATABLE
2     10120                  DOGGY RUBBER
3    10123C          HEARTS WRAPPING TAPE
4    10124A   SPOTS ON RED BOOKCOVER TAPE
5    10124G      ARMY CAMO BOOKCOVER TAPE
6     10125       MINI FUNKY DESIGN TAPES
7     10133  COLOURING PENCILS BROWN TUBE
8     10135  COLOURING PENCILS BROWN TUBE
9     11001   ASSTD DESIGN RACING CAR PEN

## 4. Lưu dữ liệu giao dịch đã làm sạch

File này giữ dữ liệu theo từng dòng sản phẩm trong hóa đơn, dùng để kiểm tra lại quá trình tiền xử lý khi cần.

In [5]:
processed_transactions_path = Path("data/processed/transactions_cleaned.csv")
df.to_csv(processed_transactions_path, index=False)

print(f"Da luu du lieu da lam sach tai: {processed_transactions_path}")
df.head()

Da luu du lieu da lam sach tai: data\processed\transactions_cleaned.csv

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

## 5. Tạo dữ liệu basket

Ở bước này, nhóm gom các sản phẩm trong cùng một `InvoiceNo` thành một basket. Mỗi basket loại bỏ sản phẩm trùng trong cùng hóa đơn và sắp xếp tên sản phẩm để kết quả ổn định khi chạy lại.

Cột `Items` được lưu bằng JSON list. Cách này an toàn hơn nối chuỗi bằng dấu phẩy, vì trong bộ dữ liệu có tên sản phẩm chứa dấu phẩy.

In [6]:
baskets = df.groupby("InvoiceNo")["Description"].apply(
    lambda x: json.dumps(sorted(set(x)), ensure_ascii=False)
).reset_index()
baskets.columns = ["InvoiceNo", "Items"]

baskets_path = Path("data/processed/baskets.csv")
baskets.to_csv(baskets_path, index=False, encoding="utf-8-sig")

print(f"Da luu file basket tai: {baskets_path}")
print(f"Tong so basket: {baskets.shape[0]}")
baskets.head()

Da luu file basket tai: data\processed\baskets.csv
Tong so basket: 19952

  InvoiceNo                                              Items
0    536365  ["CREAM CUPID HEARTS COAT HANGER", "GLASS STAR...
1    536366  ["HAND WARMER RED POLKA DOT", "HAND WARMER UNI...
2    536367  ["ASSORTED COLOUR BIRD ORNAMENT", "BOX OF 6 AS...
3    536368  ["BLUE COAT RACK PARIS FASHION", "JAM MAKING S...
4    536369                       ["BATH BUILDING BLOCK WORD"]